### PR TITLE
Upgraded Demo App to support appwrite latest version

### LINKED ISSUE #4275: 🪄 Upgrade ’demo-watertracker-with-flutter’ to Appwrite 1.0
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-watertracker-with-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-watertracker-with-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-watertracker-with-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by DevTomilola-OS**
## What does this PR do?

Upgraded flutter library to support appwrite latest version.

## Test Plan

I reviewed and upraded the flutter library to suuport appwrite latest version before running.

## Related PRs and Issues

[closes issue#4275](https://github.com/appwrite/appwrite/issues/4275)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by codercatdev — CHANGES_REQUESTED** [review]
@DevTomilola-OS please see the file `lib/data/service/api_service.dart` this needs updates for types.
Please also see 

```
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/ajonp/web/appwrite/demo-watertracker-with-flutter/android/app/build.gradle:
android {
  compileSdkVersion 33
  ...
}
```

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by christyjacob4** [comment]
@DevTomilola-OS please address the comments

**Comment by codercatdev** [comment]
@DevTomilola-OS were you able to make this update?

**Comment by christyjacob4** [comment]
@DevTomilola-OS thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

I'm closing this PR as there has not been any activity in here for a while. If you'd like to work on it again, please feel free to create a new PR.

**Pull request closed without merging**
